#Cache the predicate instances used in multipart models
cacheMultipartPredicates = true
#Replace the blockstate neighbor table
replaceNeighborLookup = true
#Do not store the properties of a state explicitly and read themfrom the replace neighbor table instead. Requires replaceNeighborLookup to be enabled
replacePropertyMap = true

